"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

format = """
[](color_orange)\
$os\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_ruby)\
$git_branch\
$git_status\
[](fg:color_ruby bg:color_berry)\
$dotnet\
$elixir\
$deno\
$ruby\
$rust\
$bun\
$golang\
$nodejs\
$python\
[](fg:color_berry bg:color_bg3)\
$docker_context\
$conda\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'ruby_slate'

[palettes.ruby_slate]
color_fg0    = '#f8f8f2' # Bright off-white
color_bg1    = '#282c34' # Dark slate
color_bg3    = '#3e4452' # Medium grey
color_ruby   = '#991b1b' # Deep Ruby Red (Git section)
color_berry  = '#be123c' # Bright Berry (Language section)
color_green  = '#a7f3d0' # Success (Emerald tint)
color_orange = '#4b5263' # OS Background (Dark Steel)
color_red    = '#ff5555' # Error
color_yellow = '#5c6370' # Directory Background (Slate)

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Macos = "󰀵"

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_ruby"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_ruby)]($style)'

[git_status]
style = "bg:color_ruby"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_ruby)]($style)'

[ruby]
symbol = ""
style = "bg:color_berry"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_berry)]($style)'

[bun]
symbol = "󰛦"
style = "bg:color_berry"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_berry)]($style)'

[nodejs]
symbol = ""
style = "bg:color_berry"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_berry)]($style)'

[rust]
symbol = ""
style = "bg:color_berry"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_berry)]($style)'

[golang]
symbol = ""
style = "bg:color_berry"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_berry)]($style)'

[python]
symbol = ""
style = "bg:color_berry"
format = '[[ $symbol( $version) \($virtualenv\) ](fg:color_fg0 bg:color_berry)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:color_fg0 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
